name:                   frontend
version:                0.1.0.0
default-extensions:     NoImplicitPrelude

dependencies:
  - base
  - common
  - containers
  - postlude
  - reflex-dom
  - text

executables:
  frontend:
    main: Main.hs
    source-dirs:
      - app
      - src
