name:                   backend
version:                0.1.0.0
default-extensions:     NoImplicitPrelude

dependencies:
  - base
  - common
  - lucid
  - postlude
  - servant-lucid
  - servant-server
  - text
  - warp

executables:
  backend:
    main: Main.hs
    source-dirs:
      - app
      - src
