name:                   backend
version:                0.1.0.0
default-extensions:     NoImplicitPrelude

dependencies:
  - aeson
  - base
  - common
  - lucid
  - opaleye
  - postgresql-simple
  - postlude
  - product-profunctors
  - servant-lucid
  - servant-server
  - text
  - time
  - warp

executables:
  backend:
    main: Main.hs
    source-dirs:
      - app
      - src
